apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp
    version: 1.0.0
    env: prod
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: ['sh', '-c', 'echo Welcome to Kubernetes! && sleep 3600']
