service: aws-node-rest-api-project
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
functions:
  hello:
    handler: src/hello.handler
    events:
    - Aws.Http:
      path: /
      method: get
resources:
  Resources:
    ToDoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ToDoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S # string
        KeySchema: # defines the primary key
        - AttributeName: id
          KeyType: HASH