apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
  labels:
    name: hello-world
spec:
  completions: 10
  parallelism: 5
  template:
    spec:
      containers:
        - name: hello-world
          image: hello-world
      restartPolicy: OnFailure
